version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf/:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"

  vue-app:
    build: ./client
    image: wforbes87/vue-app
    ports:
      - "8080:8080"

  node-app:
    build: ./
    image: wforbes87/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=wforbes
      - MONGO_INITDB_ROOT_PASSWORD=thepassword
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
volumes:
  mongo-db: